name: auto sign1
 
on:
    push:
        branches:
            - master
    schedule:
        - cron: '30 13,23 * * *'
env:
    TZ: Asia/Shanghai

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Set go
              uses: actions/setup-go@v2
              with:
                go-version: '^1.14'
            - name: hifini auto sign in
              env:
                COOKIE: ${{ secrets.COOKIE }}
              run: go run main.go
